name: Action

on:
  push:

jobs:
  extract_latest_version_of_ni_toolchain:
    runs-on: ubuntu-24.04
    outputs:
      version: ${{ steps.extract_latest_version.outputs.version }}

    steps:
      - id: extract_latest_version
        run: |
          VERSION="$(
            curl https://www.ni.com/ja/support/downloads/drivers/download.ni-visa.html |
              grep -Po 'https://download.ni.com/support/nipkg/products/ni-v/ni-visa/.*?/offline/ni-visa_.*?_offline.iso' |
              sort |
              tail -n 1 |
              sed 's_/_ _g' |
              awk '{ print $8 }'
          )"
          echo "latest version: $VERSION"
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"

  main:
    runs-on: windows-2025
    needs: extract_latest_version_of_ni_toolchain
    steps:
      - name: Print version
        run: |
          $env:NI_VER="${{ needs.extract_latest_version_of_ni_toolchain.outputs.version }}"
          $env:NI_EXE="ni-visa_$env:NI_VER_online.exe"
          $env:NI_URL="https://download.ni.com/support/nipkg/products/ni-v/ni-visa/$env:NI_VER/online/$env:NI_EXE"

          echo "Download $env:NI_EXE ($env:NI_VER) from $env:NI_URL"
          Invoke-WebRequest "$env:NI_URL" -OutFile "$env:NI_EXE"

          Start-Process -FilePath "$env:NI_EXE" -ArgumentList "--quiet", "--accept-eulas", "--prevent-reboot" -Wait

          dir C:\Windows\System32



